spring:
  profiles.active: dev

---
############################
# PROFILE DEV DEFAULT
############################
spring:
  profiles: dev

management:
  port: 9301
  address: 127.0.0.1

logging:
  file: logs/default_app.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: WARN
    guru.springframework.controllers: WARN
    org.hibernate: WARN

---
############################
# PROFILE TEST
############################
spring:
    profiles: test

management:
  port: 9002
  address: 127.0.0.1

logging:
  file: logs/test_app.log
  pattern:
    file: "%d %-5level [%thread] %logger{0} : %msg%n"
  level:
    org.springframework.web: WARN
    guru.springframework.controllers: WARN
    org.hibernate: WARN

---
############################
# PROFILE UAT
############################
spring:
   profiles: uat

---
############################
# PROFILE PRODUCTION MYSQL
############################
spring:
  profiles: prod

management:
  port: 9002
  address: 127.0.0.1

logging:
  file: logs/production_app.log
  pattern:
    file: "%d %-5level [%thread] %logger{0} : %msg%n"
  level:
    org.springframework.web: WARN
    guru.springframework.controllers: WARN
    org.hibernate: WARN

---
############################
# PROFILE PRODUCTION ORACLE
############################
spring:
  profiles: prod-oracle

logging:
  file: logs/production_app.log
  pattern:
    file: "%d %-5level [%thread] %logger{0} : %msg%n"
  level:
    org.springframework.web: WARN
    guru.springframework.controllers: WARN
    org.hibernate: WARN